name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obetendo o codigo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção e envio da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            thiagoleal201/devops4dev-review:v${{ github.run_number }}
            thiagoleal201/devops4dev-review:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Obetendo o codigo
        uses: actions/checkout@v4

      - name: Configuração do Kubectl
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deployment da aplicação
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
              k8s/deployment.yml
          images: |
            thiagoleal201/devops4dev-review:v${{ github.run_number }}
